language: java
jdk:
  - oraclejdk8
addons:
  apt:
    packages:
      - oracle-java8-installer

sudo: false
script: mvn clean package
before_deploy:
  - "cd central"
  - "ls"
deploy:
  provider: heroku
  api_key: 4b5e5055-fa98-4130-a9d0-9a8aa4fd0e88
  app: central-traffic-light